name: Update Current Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: self-hosted
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest