name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python_lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Configure Enivronment
      run: |
        python -m venv venv
        source ./venv/bin/activate
    - name: Install CLI
      run: pip install "./cli[dev]"
    - name: Install Viewer
      run: pip install "./viewer[dev]"
    - name: Test Tools
      run: |
        validate-text -t "1233 asdasd"
        validate-text -t "1233asdasd"
        compile-text -t "1234 asdasd"