name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  texttools_cli:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.pull_request.labels.*.name, 'Schema CLI') }}"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'
    - name: Install CLI
      run: |
        pip install "./cli"
        pip install "./viewer"
        pip list -v
    - name: Test Tools
      run: |
        validate-text -t "1233 asdasd"
        validate-text -t "1233asdasd"
        compile-text -t "1234 asdasd"
        generate-page -t "hello world"